Fix broken page3 due to type inconsistency
`result` was Array(0), which wasn't properly evaluating to false.

Error was:

    TypeError: Cannot read property 'toString' of undefined
    Page3._checkContent
    src/components/page3/page3.tsx:145
      142 | const idx = this.content.cards.findIndex(
      143 |   (level) => level.levelId === newLevelId && level.type === newType
      144 | );
    > 145 | this.levelDescription = this.content.cards[idx].header.replace(
          | ^  146 |   '{Q}',
      147 |   this.content.cards[idx].quantity.toString()
      148 | );