[TEST] Fix failing assertions due to rounding differences
Errors were:

  AssertionError: Expected "200891864364766493493" to be within [200892000000000000000,200893000000000000000]

  AssertionError: Expected "200891864364766493493" to be within [200892000000000000000,200893000000000000000]